### PR TITLE
Couple of updates

### PR DESCRIPTION
**Pull request by suvorov21**
1. add getFWHM method for ROOT histoes utils
2. Add a custom functor for the average computation over a vector. The default one is the vector value, so back compatibility is there.

### CODE REVIEW

**Comment by nadrino** [comment]
Nice additions!

For the FWHM, can you change the naming of the function to follow the camel convention? Also can you add a more explicit name to show that it's related to histograms? For example you could go with `getHistogramFwhm()`.

The camel convention makes accronyms look a bit weard, but it stays lisible when we chain with another trailing word

**Comment by suvorov21** [comment]
Hey! No problem, done!

**Comment by nadrino** [comment]
Cool thank you! :)

**Comment by nadrino** [comment]
Is it ready to merge? 😛

**Comment by suvorov21** [comment]
> Is it ready to merge? 😛

Hope so :)

**Pull request merged**
